### PR TITLE
Revision in 30k portuguese dictionary

### PR DESCRIPTION
**Pull request by alexandre-mbm**
To append it to branch named `Portuguese`, but **NO merge it now.** _Work in progress..._

---

@JuliusSweetland, I want to make this manual work on your wordlist with 30k entries, even having antoher plans from ENE/OptiDic#2, just to prevent problems with licenses of multiples sources data, and also to achieve rapid results in this week yet.

I am using the method showed in https://github.com/OptiKey/OptiKey/issues/234#issuecomment-260849021.

- [x] A ‒ @alexandre-mbm
- [x] B
- [x] C
- [x] D
- [x] E
- [x] F
- [x] G
- [x] H
- [x] I
- [x] J
- [x] L
- [x] M
- [x] N
- [x] O
- [x] P
- [x] Q
- [x] R ‒ @alexandre-mbm ↑
- [x] S ‒ @alandbm ↓
- [x] T
- [x] U
- [x] V
- [x] X
- [x] W
- [x] Z ‒ @alandbm, you can start from back to forward. Mark* the done and send me the file.

\* Other interested volunteers, talk to me please.

After all punctual fixes, I still will sort all. But after only.

### CODE REVIEW

**Comment by alexandre-mbm** [comment]
Persons skilled in Git can make pull requests at ENE/OptiKey#4. I will manage their commits and I will move them to here (by feeding repeatedly the branch).

**Comment by JuliusSweetland** [comment]
Before you spend a lot of time on this I'll try to generate you a new
dictionary tonight. Manually editing a whole dictionary will take you ages,
so let's call that plan b.

**Comment by alexandre-mbm** [comment]
@JuliusSweetland, the plan B is make a manipulator by using C# in according the defined in ENE/OptiDic#2. But for now (for this week that is ending) I am satisfied in work your 30k dictionary as OptiKey's patrimony free of legal issues. Don't worry. This effort for me is okay. My father need autocompletion with urgency. Note that I am at 42# of the revision already!

**Comment by alandbm** [comment]
"Z" and "V" done. 
You can check in my dropbox: https://www.dropbox.com/s/agmrir09y9jf2n6/Dicion%C3%A1rio%20Optikey%20ptbr.txt?dl=0

**Comment by alandbm** [comment]
"U" done

**Comment by alandbm** [comment]
https://www.dropbox.com/s/p1oc1trseys26td/Dicion%C3%A1rio%20Optikey%20ptbr%20UFT-8.txt?dl=0
New link

**Comment by alandbm** [comment]
"T" Done

**Comment by JuliusSweetland** [comment]
@alexandre-mbm @alandbm Good work. I can review and create a new pre-release of OptiKey with this new dictionary when you're happy.

**Comment by alexandre-mbm** [comment]
@JuliusSweetland, thanks. After all letters of alphabet, me and @alandbm will review the parts done by  each other, then I will command `sort -u` and then you could get it.

**Comment by alexandre-mbm** [comment]
@JuliusSweetland, finished!

We will not make that new check. Just was sorted. My brother is busy and I am tired. But the quality is very good, it have increased much. You can merge it into `Portuguese` branch now.

**Comment by alexandre-mbm** [comment]
It is done, despite me e my brother did not review each other's work.

**Comment by JuliusSweetland** [comment]
Ok good stuff. I will review and merge it in a minute

**Comment by JuliusSweetland** [comment]
Great work guys. I'll create a pre-release version of OptiKey now

**Pull request merged**
