### PR TITLE
Add Kalman Filter to gaze data

### PR DESCRIPTION
**Pull request by mrpmorris**

### CODE REVIEW

**Comment by yahnatan** [comment]
Awesome! Any chance you could give an interested OptiKey user a sense of the overall effect of this addition?

**Comment by alexandre-mbm** [comment]
[Kalman filter](https://en.wikipedia.org/wiki/Kalman_filter) by Wikipedia.

**Comment by alexandre-mbm** [comment]
Was it tested? Were the gains tested?

**Comment by yahnatan** [comment]
> Was it tested? Were the gains tested?

+1 to these questions

**Comment by JuliusSweetland** [comment]
I plan to merge this in this week with a new setting to turn this on/off as an optional additional layer of client side smoothing. I will test the impact when I do this and report back.

If you would like to test yourselves you should be able to merge in this pull request using the command line instructions:

```
Step 1: From your project repository, check out a new branch and test the changes.

git checkout -b mrpmorris-master master
git pull https://github.com/mrpmorris/OptiKey.git master
Step 2: Merge the changes and update on GitHub.

git checkout master
git merge --no-ff mrpmorris-master
git push origin master
```

**Comment by JuliusSweetland** [comment]
Merged - thanks Peter! I'll include this in the next version of OptiKey, which will also include a couple of bug fixes and a release candidate of Korean.

**Pull request merged**
