### PR TITLE
Make "Manual Mode" usable if eye tracker's failed to launch

### PR DESCRIPTION
**Pull request by Chopinsky**
This PR is aimed to resolve issue #408, where if the eye tracker can't be activated (e.g. the device is not connected, the device's failed to initialize, etc.), the input service isn't properly resumed in the initialization process, and as a result, users won't be able to switch to "Manual Mode" because the shield count is incorrectly set during the initialization process. 

The root cause is actually the same to issue #409: the eye tracker service is initialized before the `ToastNoticifcationPopup` is loaded; and when the activation failed, we would try to raise a `ToastNotificationPopup` to inform the users, however, since the popup's not available yet at that moment, the popup will not be raised. But the effort to raise the popup have added a shield on top of the keyboard, but the shield is never lowered (the callback to the popup is responsible for lowering the shield, since the popup is never launched, the callback is never invoked either), which will then block the workflow to switch to the manual mode.

The solution is to add rail guards around the error handlers: 1. if the popup hasn't been loaded yet, don't try to raise it and bring up the shield; 2. if someone tries to bring up the popup prematurely in the future, we will fallback on calling the callback directly to clean anything up, such that we won't accidentally block the keyboard because the clean-up callback is not raised. 

Be noted that this is not the full solution to issue #409, it's kind of difficult to make sure the popup is loaded before all the services are initialized -- there're quite entangled code dependencies and assumptions made in the app-launching code, so I would envision a little bit more sophisticated fix to issue #409: (the easier solution) save off all the errors encountered during service initialization, then bring up the toast notification after the main window is fully loaded (before or after the splash popup); (the harder solution) if eye track devices are failed to activate, fallback to the mouse pointer mode (aka the Manual Mode).

### CODE REVIEW

**Comment by JuliusSweetland** [comment]
@Chopinsky Thanks for this. If you have time would it be possible to look into a fix for #409 as that would solve this issue in a more complete way. This fix, while effective, is a bit of a work around. I'm not sure the user hearing the error tone, but with no indication as to why, would be ideal.

**Comment by Chopinsky** [comment]
I've some rough ideas on how to implement the "easy solution" I mentioned, will work on that.

**Comment by Chopinsky** [comment]
New commit allow us to cache pre-load error messages, and prompt them to end users in the roast notifications right after the splash screen (or if no splash screen, right after launching).

**Comment by JuliusSweetland** [comment]
@Chopinsky Like it, thank you! Merged.

**Pull request merged**
