### PR TITLE
Ongoing fixes

### PR DESCRIPTION
**Pull request by kmcnaught**
Several things from https://github.com/OptiKey/OptiKey/projects/2, commit messages speak for themselves

### CODE REVIEW

**Review by kmcnaught — COMMENTED** [review]
@JuliusSweetland This looks like a bug but wasn't causing a problem, could you please pass your eyes over it too

**Review by AdamRoden — COMMENTED** [review]
Regarding key selection while point selection is underway, how does this behave for you? I did the exact same thing, and when I tested I was able to select keys during point selection, but the selected keys never seemed to be acted on. This lead me to believe we may need to implement a queue so newly selected actions fire after the point selection action completes.

**Comment by kmcnaught** [comment]
force-push to fix last commit and remove WIP re point selection

@AdamRoden I'd only just got that far as a first step, still investigating...

**Comment by JuliusSweetland** [comment]
> 
@kmcnaught I can't see exactly what you are referring to, but all commits look good to me. Thanks.

**Comment by kmcnaught** [comment]
@JuliusSweetland feel free to have a play with left click locking feature here. I've braindumped my current thoughts re: UX / next steps over at https://github.com/OptiKey/OptiKey/issues/744

**Comment by kmcnaught** [comment]
I have force pushed with squashed commits and an update to fix unit tests that broke when selection event API changed

**Comment by kmcnaught** [comment]
I just force-pushed with a revert of [fa0d466](https://github.com/OptiKey/OptiKey/pull/874/commits/fa0d46662c6bac933094cc210708df6cb4b0c140) before my work. This avoids a temporary bug introduced in fa0d which is later fixed in #871

This PR (#874) is ready for pre-release now, with the next followup being [ fa0d4666 + #871 ] for separate testing

**Pull request merged**
