### PR TITLE
Added Azure Devops CI yaml file

### PR DESCRIPTION
**Pull request by rschiefer**

### CODE REVIEW

**Comment by JuliusSweetland** [comment]
@rschiefer Looks good. Before I merge this in what do you think I should do with the existing AppVeyor CI (including the build status icon in the footer)? I could keep both?

Also does Azure send an email when the build status changes?

**Comment by rschiefer** [comment]
Yes, I think keep both until we are happy with the Azure Pipeline.  Yes, it can be configured to email build status notifications.

**Comment by JuliusSweetland** [comment]
@rschiefer Merged. Thank you!

**Comment by rschiefer** [comment]
My pleasure!

**Comment by JuliusSweetland** [comment]
@rschiefer Question for you - any idea how to set up the web hooks to get the Azure Pipeline to trigger when someone checks in to master? At the moment I think the pipeline only runs when manually triggered. I tried finding instructions, but I'm hitting a bit of a brick wall.

**Comment by rschiefer** [comment]
Try this link - https://github.com/apps/azure-pipelines/installations/new

**Comment by rschiefer** [comment]
If that one doesn’t work try https://github.com/marketplace/azure-pipelines

**Comment by rschiefer** [comment]
I had already added you as a project admin and now you are also a project collection admin.  Sorry about that.

**Comment by rschiefer** [comment]
I wasn't able to get the existing build to work but was able to create a new one with the checkin trigger.  

https://dev.azure.com/optikey/optikey/_build?definitionId=5

**Comment by rschiefer** [comment]
Yes, should trigger for commits and PRs going forward.

**Comment by JuliusSweetland** [comment]
Great thanks Robb!

**Comment by rschiefer** [comment]
Yes, for the new CI build I created yesterday.

Thanks,

Robb Schiefer
Twitter - @chief7
Blog - dotnetcatch.com
BHM.NET Meetup - https://www.meetup.com/Birmingham-NET-Meetup/

________________________________

**Comment by JuliusSweetland** [comment]
@rschiefer I've got an issue here. If I change the icon link from "[Build status](https://dev.azure.com/optikey/optikey/_build/latest?definitionId=-1)" to "[Build status](https://dev.azure.com/optikey/optikey/_build/latest?definitionId=5)" I get this:
image

But if I follow the new link I see the CI build as expected???

**Comment by JuliusSweetland** [comment]
@rschiefer I can see that you've updated the build badge on your other PR - I'll merge that in and see if that fixes things.

**Pull request merged**
