### PR TITLE
Fixes bug with transparency

### PR DESCRIPTION
**Pull request by AdamRoden**
I don't know why there is so much out of sync, but all I changed was in the last commit

### CODE REVIEW

**Comment by JuliusSweetland** [comment]
@AdamRoden I think this PR contains the commit before as well. It is showing me merge problems. I'm happy to fix them this evening, but if you cancel this, update from my master branch, and apply your transparency fix again then it should be better...

**Comment by JuliusSweetland** [comment]
@AdamRoden Hi Adam. I have created a pre-release of 2.32.0 which includes all of your changes to date. Could you please test it and confirm that it is ready for general release? https://github.com/OptiKey/OptiKey/releases/download/v2.32.0_v3/OptiKeySetup-2.32.0.exe

**Comment by AdamRoden** [comment]
It works great! However, I did find certain Action keys do not work in the context of a DynamicKey StepList. For now, at least, the StepList cannot handle KeysWhichCanBeLockedDown. In the long-term I'd like to address it properly, but for now I created a work around for the issue, and put it in a new PR.

**Comment by JuliusSweetland** [comment]
Ideal, thank you. I'll release tonight.

**Pull request merged**
