### PR TITLE
Update Resources.ja-JP.resx

### PR DESCRIPTION
**Pull request by Ishaan28malik**
Renamed  "MANUAL MODE" to a "MOUSE CONTROL MODE" 
#548

### CODE REVIEW

**Comment by Ishaan28malik** [comment]
@JuliusSweetland , i renamed the keywords I could find . Are there any more left ?

**Comment by JuliusSweetland** [comment]
@Ishaan28malik Yes, but also in this file: https://github.com/OptiKey/OptiKey/blob/591864316bb96f6ab11b2db49f1a6ac4894c2b98/src/JuliusSweetland.OptiKey.Core/Properties/Resources.resx

**Comment by Ishaan28malik** [comment]
Done

**Comment by Ishaan28malik** [comment]
@JuliusSweetland pls review

**Comment by Ishaan28malik** [comment]
ok

**Pull request merged**
