### PR TITLE
Changed some special key names (German)

### PR DESCRIPTION
**Pull request by hiwye**
* Changed scroll lock to "Rollen" as it is shown on most german keyboards
* Changed pg up and pg down to "Bild hoch" and "Bild runter" as it is shown on most german keyboards.

### CODE REVIEW

**Comment by JuliusSweetland** [comment]
@hiwye Thanks Sebastian. The new PgUp and PgDown strings are longer than the previous strings - do they still look ok on the Physical Keys keyboard? I am concerned that they will make all strings across that keyboard smaller. If so the fix is easy - just replace the space in each string with a newline.

**Comment by hiwye** [comment]
Could we just use arrows like these?
http://stackoverflow.com/a/2701226/4713557

**Comment by JuliusSweetland** [comment]
@hiwye Certainly not impossible, but I shied away from using unicode symbols in favour of using SVG graphics (using Paths in WPF) as the latter gave me much more control over sizing. Do the new strings impact the Physical keyboard key labels then?

**Comment by hiwye** [comment]
@JuliusSweetland This now really closely resembles the german keyboard buttons.
Sizing works great aswell.

**Comment by JuliusSweetland** [comment]
@hiwye Ok great. I'll take a look over the weekend and look to include this change in the next release (v2.3.1).

**Pull request merged**
