### PR TITLE
Issue #520 UA localization

### PR DESCRIPTION
**Pull request by Larkailya**
Hi everyone!
You have implemented the Ukrainian localization. We would be glad to see this locale in the project.

### CODE REVIEW

**Comment by JuliusSweetland** [comment]
@Larkailya Excellent! Thank you. I will start reviewing this and release this as soon as I have completed some testing. If I have any changes or questions I will post them here. You should get an automatic email notifying you if I do this.

**Comment by JuliusSweetland** [comment]
@Larkailya When testing I've noticed that the accent key (below) does not restrict which keys can be combined with the accent:
image

In Russian, for example, when you select that key it limits the letters on which the accent can be applied to these:
image

Should Ukrainian be the same? If so could you please add the logic? It lives in KeyEnabledStates.cs - here is the Russian equivalent: https://github.com/OptiKey/OptiKey/blob/c15f414ad744e455bda9b1198f7a7b265bb0750b/src/JuliusSweetland.OptiKey/Models/KeyEnabledStates.cs#L669

Once happy could you please update this PR, or close it and submit a new one?

Apart from that one thing I am happy to create a pre-release for you to test once you've made this change and then we can get this out ASAP. Thanks very much.

**Comment by Larkailya** [comment]
Well, sorry, I missed it.

**Comment by JuliusSweetland** [comment]
@Larkailya That looks better. Next thing I've found - I don't think the combination of the accent to the letters is working correctly. If you try typing the accent key and then the "a" key it will combine as expected, but I believe a different "a" is being used as the value of the key, resulting in the accent + the "a" key not combining into 1 character. You can see this if you debug this line: https://github.com/OptiKey/OptiKey/blob/master/src/JuliusSweetland.OptiKey/Services/KeyboardOutputService.cs#L496

I would expect the accent to combine (using Unicode composition) with each letter to form 1 character (the letter with an accent). What is currently happening is the accent + the letter is resulting in a combined character that is actually 2 characters long. This results in odd behaviour with the auto spaces - keep typing and a space will be inserted between the accented letter and the next letter - this is wrong.

I've tried changing the latin letters over to the ones from my keyboard (a,e,o) and it starts to work correctly, but I can't do this with the other Ukrainian letters. Could you take a look.

I would also like to check that you mean to include the double dotted i in the letters which can have an accent added to them.

**Comment by Larkailya** [comment]
@JuliusSweetland Well, After debugging, I noticed that this bug is also reproducible on the Russian keyboard layout. In other languages that do not use Cyrillic characters, there is no such problem.
photo_2018-11-10_17-58-26

I could be wrong. But during debugging, I noticed that there is a boolean variable suppressNextAutoSpace which takes the value of truth if this condition is met

https://github.com/OptiKey/OptiKey/blob/1ed3aadca0060a700e7b133c36a294de2f967b51/src/JuliusSweetland.OptiKey/Services/KeyboardOutputService.cs#L541

In a language without Cyrillic characters, this condition is true, because the length of variable `newText.Length` is equal one character, but with Cyrillic, this condition is false (is equal two characters)

photo_2018-11-10_18-21-31

So the value of a boolean variable is not true.

Well, after a little research on this problem, I can offer this solution
```csharp
else if(new StringInfo(lastProcessedText).LengthInTextElements == 1
         && new StringInfo(newText).LengthInTextElements == 1
         && !lastProcessedTextWasSuggestion
         && !(keyStateService.KeyDownStates[KeyValues.MultiKeySelectionIsOnKey].Value.IsDownOrLockedDown() && char.IsLetter(newText.First())))
```
This solves the problem of adding space in languages using Cyrillic characters along with an accent.

I am unsure if this is the right solution. Ready for discussion.

**Comment by JuliusSweetland** [comment]
@Larkailya That's a good fix. I would be interested to know if the underlying problem with the characters not combining could be fixed as well. I suspect there are multiple instances of the same letters in the Unicode page - some which combine with diacritic marks and some which don't. English is the same in that respect.

**Pull request merged**
