### PR TITLE
Fix bug in dynamic key locking logic.

### PR DESCRIPTION
**Pull request by AdamRoden**

### CODE REVIEW

**Comment by JuliusSweetland** [comment]
@AdamRoden Good stuff. Is this everything that was outstanding? I.e. should I create a new pre-release tomorrow pending a release as soon as everyone is happy?

**Comment by AdamRoden** [comment]
Yes. Now would be a good time to do a release. I've been very pleased with
everything.

Adam Roden

**Comment by JuliusSweetland** [comment]
@AdamRoden Cool. I've had a bug report come through today so I'll see if that needs to be fixed and then prepare something asap.

Thanks, as always.

**Comment by JuliusSweetland** [comment]
@AdamRoden Oh, and there were also updates to dynamic keyboards required, or are they no longer needed?

**Comment by AdamRoden** [comment]
@JuliusSweetland I will prepare an updated set of sample keyboards for inclusion in the release.

**Pull request merged**
