### PR TITLE
Disable locking behavior during point fixation in favor of continuous…

### PR DESCRIPTION
**Pull request by AdamRoden**
… smooth motion

### CODE REVIEW

**Comment by JuliusSweetland** [comment]
I like this. @kmcnaught Are you happy with this change? There are a lot of concurrent changes and discussions going on so I'd like input from everyone before I blindly merge things in.

**Comment by AdamRoden** [comment]
This should have been the first place I went when Kirsty brought up the issue of the cursor not being smooth. 
Also, some food for thought, perhaps it is more appropriate to have our input stream update be purely Kalman based, and to have addition slow-motion and cursor locking effects applied either here, or if the Magnetic Cursor is active, in its event handler. 
We'll see what Kirsty says.

**Comment by JuliusSweetland** [comment]
Interesting ideas. If we go down that route my initial thought would be to
toggle the KF on/off (or increase/decrease its effect) from the code which
opens/closes the magnified popup or starts/stops the magnetic cursor, so
the input service handles all requests like that.

**Comment by AdamRoden** [comment]
So, I guess this little change only works nicely when paired with the Kalman Filter. After more testing without raw unfiltered points, the results were ugly.

**Comment by JuliusSweetland** [comment]
Maybe we could work out the minimum amount of smoothing required to be able
to turn off this locking and link the two behaviours?

**Comment by kmcnaught** [comment]
I'm 100% behind the idea of removing the locking behaviour, but I don't think this commit does it correctly - have you tried my attempt? https://github.com/kmcnaught/OptiKey/commit/5f6b7f9e6921ea1d0ad6fdb2916fa18b558f4b57 - you may wish to cherry-pick the commit onto your preferred filtering setup. 

When I try this PR I get quite jittery behaviour - I think you're correcting the position of the cursor visualisation rather than the point fixation centre. If you remove lockon on the point fixation centre instead (as per 5f6b7f) then the cursor naturally follows

**Comment by AdamRoden** [comment]
@kmcnaught Your change is better. PR that.

**Pull request closed without merging**
