### PR TITLE
Add CommuniKate keyboard for issue #324

### PR DESCRIPTION
**Pull request by zelmon64**
The default CommuniKate layout is included with OptiKey so all that is needed is to enable CommuniKate from the Words tab of the management console. The CommuniKate keyboard can then be access either by selecting it in that tab or by pressing the "CK" key on the Alpha and ConversationAlpha keyboards.

### CODE REVIEW

**Comment by JuliusSweetland** [comment]
@zelmon64 I've only had a chance to skim the change. So far, so good, but I have a few questions...

1. It isn't building against master
2. Should the computercontrol.obf key link to the WebBrowsing keyboard? What about the mouse keyboard?
3. What does the CommuniKateKeyboard function key do? I haven't merged the change and it's difficult to see as 1750 files have changed!
4. What do you think about these suggestions from earlier (I have to copy/paste - I can't link to my comment):

1.Unless I am wrong I don't think CK is designed for typing into other applications and is instead a speaking tool. If that's accurate I am picturing 3 setting:
a) Enable CommuniKate? - If disabled the ConversationAlpha keyboard looks as it does now. If enabled then there should be a key on the ConversationAlpha keyboard in the same way as there is a link to the Yes/No keyboard (if ConversationConfirmEnable==true).
b) Replace Conversation keyboard? If disabled then you get to CK from the ConversationAlpha key. If enabled then the CK keyboard IS the conversation keyboard and you get to it from the Menu, or by setting the startup keyboard to CommuniKate (or ConversationAlpha, which would redirect to CommuniKate).
c)CommuniKate Only Mode - we could just use the existing Conversation Only Mode setting, which forces the startup keyboard to Conversation Alpha and changes the BACK button to a QUIT button. We should have a similar mechanism so the user cannot BACK out of the CommuniKate keyboard if they are in CommuniKate Only/Conversation Only Mode.

2.Don't link to the CK keyboard from the standard Alpha keyboards as these are predominantly for typing.

**Comment by zelmon64** [comment]
@JuliusSweetland 

1. I've rebased against master. I'm not sure why AppVeyor is failing. It doesn't seem related to anything I've changed so I don't know why it's no longer building.

2. I'd forgotten about the mouse keyboard and agree it's a better fit so have linked that one instead.

3. The the CommuniKateKeyboard function key is used to switch from the (Conversation)Alpha and ConversationNumeric keyboards to CommuniKate. In Conversation mode this can also be done with the back key if the initial keyboard was CommuniKate. If OptiKey is closed while not with CommuniKate in use then this function key is the easy way to enter CommuniKate (otherwise it has to be done through the management console).

#### 4.1.
a. This had already been implemented.
b. This had also already been implemented. 
c. This had since been implemented.

#### 4.2.
I believe CommuniKate may be useful for typing so when it's not maximised I think it should link to the standard keyboards.

**Comment by zelmon64** [comment]
@JuliusSweetland I've pushed the new OBZ method and I noticed a new file (`.vs/config/applicationhost.config`) that I seem to have added a few day ago. Is it like `appconfig` and gets auto generated and has to be deleted?

**Comment by JuliusSweetland** [comment]
@zelmon64 I'll add some more detail in a minute, but here is a dump of the failing build:

WORKING BUILD EXAMPLE: https://ci.appveyor.com/project/OptiKey/optikey/build/2.2.5.276/job/2rfl7vlyohf57h27

FAILING BUILD EXAMPLE: https://ci.appveyor.com/project/OptiKey/optikey/build/job/c8o544r1v7tmn9gi
...
Restoring NuGet package MahApps.Metro.1.1.2.
...
GET https://www.nuget.org/api/v2/Packages(Id='MahApps.Metro',Version='1.1.2')
...
OK https://www.nuget.org/api/v2/Packages(Id='MahApps.Metro',Version='1.1.2') 89ms
...
GET https://www.nuget.org/api/v2/package/MahApps.Metro/1.1.2
...
OK https://www.nuget.org/api/v2/package/MahApps.Metro/1.1.2 79ms
...
Installing MahApps.Metro 1.1.2.0.
...
Adding package 'MahApps.Metro.1.1.2' to folder 'C:\projects\optikey\packages'
...
Added package 'MahApps.Metro.1.1.2' to folder 'C:\projects\optikey\packages'
...
Primary reference "MahApps.Metro, Version=1.5.0.23, Culture=neutral, PublicKeyToken=f4fb5a3c4d1e5b4f, processorArchitecture=MSIL".
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "MahApps.Metro, Version=1.5.0.23, Culture=neutral, PublicKeyToken=f4fb5a3c4d1e5b4f, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\projects\optikey\src\JuliusSweetland.OptiKey\JuliusSweetland.OptiKey.csproj]

For SearchPath "{CandidateAssemblyFiles}".
          Considered "..\..\ext\myGaze\myGazeAPI.dll", but its name "myGazeAPI" didn't match.
          Considered "..\..\ext\Bass\bass.dll", but its name "bass" didn't match.
          Considered "..\..\ext\TobiiEyeXSdk\Tobii.EyeX.Client.dll", but its name "Tobii.EyeX.Client" didn't match.
          For SearchPath "{HintPathFromItem}".
          Considered "..\..\packages\MahApps.Metro.1.5.0\lib\net45\MahApps.Metro.dll", but it didn't exist.
          For SearchPath "{TargetFrameworkDirectory}".
          Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\MahApps.Metro.winmd", but it didn't exist.
          Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\MahApps.Metro.dll", but it didn't exist.
          Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\MahApps.Metro.exe", but it didn't exist.
          Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\MahApps.Metro.winmd", but it didn't exist.
          Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\MahApps.Metro.dll", but it didn't exist.
          Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\MahApps.Metro.exe", but it didn't exist.
          For SearchPath "{Registry:Software\Microsoft\.NETFramework,v4.6,AssemblyFoldersEx}".
          Considered AssemblyFoldersEx locations.
          For SearchPath "{AssemblyFolders}".
          Considered "C:\Program Files (x86)\Microsoft SQL Server\140\SDK\Assemblies\MahApps.Metro.winmd", but it didn't exist.
          Considered "C:\Program Files (x86)\Microsoft SQL Server\140\SDK\Assemblies\MahApps.Metro.dll", but it didn't exist.
          Considered "C:\Program Files (x86)\Microsoft SQL Server\140\SDK\Assemblies\MahApps.Metro.exe", but it didn't exist.
          Considered "C:\Program Files (x86)\Microsoft\Contracts\PublicAssemblies\v3.5\MahApps.Metro.winmd", but it didn't exist.
          Considered "C:\Program Files (x86)\Microsoft\Contracts\PublicAssemblies\v3.5\MahApps.Metro.dll", but it didn't exist.
          Considered "C:\Program Files (x86)\Microsoft\Contracts\PublicAssemblies\v3.5\MahApps.Metro.exe", but it didn't exist.
          Considered "C:\Windows\Microsoft.NET\DirectX for Managed Code\1.0.2909.0\MahApps.Metro.winmd", but it didn't exist.
          Considered "C:\Windows\Microsoft.NET\DirectX for Managed Code\1.0.2909.0\MahApps.Metro.dll", but it didn't exist.
          Considered "C:\Windows\Microsoft.NET\DirectX for Managed Code\1.0.2909.0\MahApps.Metro.exe", but it didn't exist.
          Considered "C:\Windows\Microsoft.NET\DirectX for Managed Code\1.0.2907.0\MahApps.Metro.winmd", but it didn't exist.
          Considered "C:\Windows\Microsoft.NET\DirectX for Managed Code\1.0.2907.0\MahApps.Metro.dll", but it didn't exist.
          Considered "C:\Windows\Microsoft.NET\DirectX for Managed Code\1.0.2907.0\MahApps.Metro.exe", but it didn't exist.
          Considered "c:\Program Files (x86)\Microsoft.NET\ADOMD.NET\100\MahApps.Metro.winmd", but it didn't exist.
          Considered "c:\Program Files (x86)\Microsoft.NET\ADOMD.NET\100\MahApps.Metro.dll", but it didn't exist.
          Considered "c:\Program Files (x86)\Microsoft.NET\ADOMD.NET\100\MahApps.Metro.exe", but it didn't exist.
          Considered "C:\Windows\Microsoft.NET\DirectX for Managed Code\1.0.2902.0\MahApps.Metro.winmd", but it didn't exist.
          Considered "C:\Windows\Microsoft.NET\DirectX for Managed Code\1.0.2902.0\MahApps.Metro.dll", but it didn't exist.
          Considered "C:\Windows\Microsoft.NET\DirectX for Managed Code\1.0.2902.0\MahApps.Metro.exe", but it didn't exist.
          Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.0\MahApps.Metro.winmd", but it didn't exist.
          Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.0\MahApps.Metro.dll", but it didn't exist.
          Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.0\MahApps.Metro.exe", but it didn't exist.
          Considered "C:\Program Files (x86)\Microsoft SQL Server\120\SDK\Assemblies\MahApps.Metro.winmd", but it didn't exist.
          Considered "C:\Program Files (x86)\Microsoft SQL Server\120\SDK\Assemblies\MahApps.Metro.dll", but it didn't exist.
          Considered "C:\Program Files (x86)\Microsoft SQL Server\120\SDK\Assemblies\MahApps.Metro.exe", but it didn't exist.
          Considered "C:\Windows\Microsoft.NET\DirectX for Managed Code\1.0.2904.0\MahApps.Metro.winmd", but it didn't exist.
          Considered "C:\Windows\Microsoft.NET\DirectX for Managed Code\1.0.2904.0\MahApps.Metro.dll", but it didn't exist.
          Considered "C:\Windows\Microsoft.NET\DirectX for Managed Code\1.0.2904.0\MahApps.Metro.exe", but it didn't exist.
          Considered "C:\Program Files (x86)\FSharp-2.0.0.0\bin\MahApps.Metro.winmd", but it didn't exist.
          Considered "C:\Program Files (x86)\FSharp-2.0.0.0\bin\MahApps.Metro.dll", but it didn't exist.
          Considered "C:\Program Files (x86)\FSharp-2.0.0.0\bin\MahApps.Metro.exe", but it didn't exist.
          Considered "C:\Windows\Microsoft.NET\DirectX for Managed Code\1.0.2911.0\MahApps.Metro.winmd", but it didn't exist.
          Considered "C:\Windows\Microsoft.NET\DirectX for Managed Code\1.0.2911.0\MahApps.Metro.dll", but it didn't exist.
          Considered "C:\Windows\Microsoft.NET\DirectX for Managed Code\1.0.2911.0\MahApps.Metro.exe", but it didn't exist.
          Considered "C:\Program Files (x86)\Microsoft.NET\ADOMD.NET\120\MahApps.Metro.winmd", but it didn't exist.
          Considered "C:\Program Files (x86)\Microsoft.NET\ADOMD.NET\120\MahApps.Metro.dll", but it didn't exist.
          Considered "C:\Program Files (x86)\Microsoft.NET\ADOMD.NET\120\MahApps.Metro.exe", but it didn't exist.
          Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.5\MahApps.Metro.winmd", but it didn't exist.
          Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.5\MahApps.Metro.dll", but it didn't exist.
          Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.5\MahApps.Metro.exe", but it didn't exist.
          Considered "C:\Windows\Microsoft.NET\DirectX for Managed Code\1.0.2910.0\MahApps.Metro.winmd", but it didn't exist.
          Considered "C:\Windows\Microsoft.NET\DirectX for Managed Code\1.0.2910.0\MahApps.Metro.dll", but it didn't exist.
          Considered "C:\Windows\Microsoft.NET\DirectX for Managed Code\1.0.2910.0\MahApps.Metro.exe", but it didn't exist.
          Considered "C:\Program Files\IIS\Microsoft Web Deploy V3\MahApps.Metro.winmd", but it didn't exist.
          Considered "C:\Program Files\IIS\Microsoft Web Deploy V3\MahApps.Metro.dll", but it didn't exist.
          Considered "C:\Program Files\IIS\Microsoft Web Deploy V3\MahApps.Metro.exe", but it didn't exist.
          Considered "C:\Windows\Microsoft.NET\DirectX for Managed Code\1.0.2906.0\MahApps.Metro.winmd", but it didn't exist.
          Considered "C:\Windows\Microsoft.NET\DirectX for Managed Code\1.0.2906.0\MahApps.Metro.dll", but it didn't exist.
          Considered "C:\Windows\Microsoft.NET\DirectX for Managed Code\1.0.2906.0\MahApps.Metro.exe", but it didn't exist.
          Considered "C:\Program Files (x86)\Microsoft.NET\ADOMD.NET\110\MahApps.Metro.winmd", but it didn't exist.
          Considered "C:\Program Files (x86)\Microsoft.NET\ADOMD.NET\110\MahApps.Metro.dll", but it didn't exist.
          Considered "C:\Program Files (x86)\Microsoft.NET\ADOMD.NET\110\MahApps.Metro.exe", but it didn't exist.
          Considered "C:\Program Files (x86)\Microsoft SQL Server\130\SDK\Assemblies\MahApps.Metro.winmd", but it didn't exist.
          Considered "C:\Program Files (x86)\Microsoft SQL Server\130\SDK\Assemblies\MahApps.Metro.dll", but it didn't exist.
          Considered "C:\Program Files (x86)\Microsoft SQL Server\130\SDK\Assemblies\MahApps.Metro.exe", but it didn't exist.
          Considered "C:\Windows\Microsoft.NET\DirectX for Managed Code\1.0.2903.0\MahApps.Metro.winmd", but it didn't exist.
          Considered "C:\Windows\Microsoft.NET\DirectX for Managed Code\1.0.2903.0\MahApps.Metro.dll", but it didn't exist.
          Considered "C:\Windows\Microsoft.NET\DirectX for Managed Code\1.0.2903.0\MahApps.Metro.exe", but it didn't exist.
          Considered "C:\Windows\Microsoft.NET\DirectX for Managed Code\1.0.2908.0\MahApps.Metro.winmd", but it didn't exist.
          Considered "C:\Windows\Microsoft.NET\DirectX for Managed Code\1.0.2908.0\MahApps.Metro.dll", but it didn't exist.
          Considered "C:\Windows\Microsoft.NET\DirectX for Managed Code\1.0.2908.0\MahApps.Metro.exe", but it didn't exist.
          Considered "C:\Program Files (x86)\Microsoft SQL Server\130\SDK\Assemblies\MahApps.Metro.winmd", but it didn't exist.
          Considered "C:\Program Files (x86)\Microsoft SQL Server\130\SDK\Assemblies\MahApps.Metro.dll", but it didn't exist.
          Considered "C:\Program Files (x86)\Microsoft SQL Server\130\SDK\Assemblies\MahApps.Metro.exe", but it didn't exist.
          Considered "C:\Windows\Microsoft.NET\DirectX for Managed Code\1.0.2905.0\MahApps.Metro.winmd", but it didn't exist.
          Considered "C:\Windows\Microsoft.NET\DirectX for Managed Code\1.0.2905.0\MahApps.Metro.dll", but it didn't exist.
          Considered "C:\Windows\Microsoft.NET\DirectX for Managed Code\1.0.2905.0\MahApps.Metro.exe", but it didn't exist.
          Considered "C:\Program Files (x86)\WiX Toolset v3.11\SDK\MahApps.Metro.winmd", but it didn't exist.
          Considered "C:\Program Files (x86)\WiX Toolset v3.11\SDK\MahApps.Metro.dll", but it didn't exist.
          Considered "C:\Program Files (x86)\WiX Toolset v3.11\SDK\MahApps.Metro.exe", but it didn't exist.
          Considered "c:\Program Files (x86)\Microsoft SQL Server\100\SDK\Assemblies\MahApps.Metro.winmd", but it didn't exist.
          Considered "c:\Program Files (x86)\Microsoft SQL Server\100\SDK\Assemblies\MahApps.Metro.dll", but it didn't exist.
          Considered "c:\Program Files (x86)\Microsoft SQL Server\100\SDK\Assemblies\MahApps.Metro.exe", but it didn't exist.
          Considered "C:\Program Files (x86)\Microsoft.NET\ADOMD.NET\130\MahApps.Metro.winmd", but it didn't exist.
          Considered "C:\Program Files (x86)\Microsoft.NET\ADOMD.NET\130\MahApps.Metro.dll", but it didn't exist.
          Considered "C:\Program Files (x86)\Microsoft.NET\ADOMD.NET\130\MahApps.Metro.exe", but it didn't exist.
          For SearchPath "{GAC}".
          Considered "MahApps.Metro, Version=1.5.0.23, Culture=neutral, PublicKeyToken=f4fb5a3c4d1e5b4f, processorArchitecture=MSIL", which was not found in the GAC.
          For SearchPath "{RawFileName}".
          Considered treating "MahApps.Metro, Version=1.5.0.23, Culture=neutral, PublicKeyToken=f4fb5a3c4d1e5b4f, processorArchitecture=MSIL" as a file name, but it didn't exist.
          For SearchPath "bin\Debug\".
          Considered "bin\Debug\MahApps.Metro.winmd", but it didn't exist.
          Considered "bin\Debug\MahApps.Metro.dll", but it didn't exist.
          Considered "bin\Debug\MahApps.Metro.exe", but it didn't exist.

ERRORS:
C:\projects\optikey\src\JuliusSweetland.OptiKey\UI\Views\Management\PointingAndSelectingView.xaml(168,22): error MC3074: The tag 'NumericUpDown' does not exist in XML namespace 'http://metro.mahapps.com/winfx/xaml/controls'. Line 168 Position 22. [C:\projects\optikey\src\JuliusSweetland.OptiKey\JuliusSweetland.OptiKey.csproj]

JuliusSweetland.OptiKey.csproj contains:

<Reference Include="MahApps.Metro, Version=1.1.2.0, Culture=neutral, PublicKeyToken=f4fb5a3c4d1e5b4f, processorArchitecture=MSIL">
  <SpecificVersion>False</SpecificVersion>
  <HintPath>..\..\packages\MahApps.Metro.1.1.2.0\lib\net45\MahApps.Metro.dll</HintPath>
</Reference>

**Comment by zelmon64** [comment]
@JuliusSweetland it turns out a few bits in `JuliusSweetland.OptiKey.csproj` had gotten messed up (not sure how). I'm so glad I converted to using the OBZ archive file instead of all the unpacked OBF and images. It made it so much easier to find the difference.

**Comment by zelmon64** [comment]
I wondered what would happen if I tried to delete `applicationhost.config` and the answer was that it made no difference as far as I cold tell.

**Comment by JuliusSweetland** [comment]
I couldn't see (at work today) what the project file differences were, but
the build was restoring one version of MahApps, but then trying to use
another. Thank you for finding the issue.

**Comment by JuliusSweetland** [comment]
Testing feedback:

Overall it looks like a really good PR. I've very excited by the new functionality. OptiKey is really growing from these recent PRs. Here are my questions/requests for discussion:

1.I think some of these settings could be moved around/reworded slightly to make it clearer what they mean:

image

a)"Use CommuniKate keyboard layout" should maybe read "Replace Alpha keyboard with CommuniKate"
b)"Replace Alpha keyboard with CommuniKate" should be directly under "Enable CommuniKate keyboard layout"
c)"Use simplified keyboard layout" should maybe read "Replace Alpha keyboard with simplified keyboard layout"
d)"Use alphabetical keyboard layout" should maybe read "Use alphabetical alpha keyboard layout"
e)These 3 settings (that change the alpha keyboard layout) should be mutually exclusive - if any is selected then the other two options should be set to false and not visible.

2.I think the output control (scratchpad etc) is too small. Can we rebalance the rows (by just adding a row and letting the output control span the same row height as all the CommuniKate keys. It feels a bit small at the moment.

image

3.The CommuniKate key selection animation colour is black - is this the colour that other CommuniKate devices use? It looks a bit odd/wrong to my eyes.

4.Once you enable CommuniKate, but leave UseCommuniKateKeyboardLayout=false, the first time you us the "CK" key then UseCommuniKateKeyboardLayout is set to true anyway. This makes it impossible to go back to the Alpha keyboard from the menu.  I see you can get back there from 'My day' -> 'Spelling' (or 'My day' -> '123' to get the Numeric keyboard), but I still think this behaviour is wrong. If you quit OptiKey and then open it again I would expect the usual Alpha keyboard, but you get CommuniKate as your startup keyboard instead.

5.Should 'Spelling', '123', 'Computer Control' etc be under 'My day'? I don't know the boards, but this seems odds to me.

6. 
a)'Delete word' key outputs "Delete Word" rather than actioning the BackMany function.
b)This also begs the question; do we need the BackMany key if users will be expecting to use the CommuniKate 'Delete word' key? I don't have a strong opinion either way, just asking the question.

7.'Computer control' key outputs "Computer control" rather than changing the keyboard. Is this correct?

8.The changes made to Android_Dark.xaml need to be mirrored (with different colours) into Android_Light.xaml


And some cleanup bits and bobs:

1. KeyboardCurrentContext setting looks to be unused - can we delete it?
2. Rename HandleMultiPropertyKeySelectionResult to HandleStringAndFunctionKeySelectionResult
3. Rename UseCommuniKatedKeyboardLayoutIsVisible to UseCommuniKateKeyboardLayoutIsVisible
4. FunctionKeys.KeyboardContext looks to be unused - can we delete it?


Otherwise it looks really really promising! Great work William. Much appreciated!

**Comment by zelmon64** [comment]
@JuliusSweetland Thanks for all this feedback!

> 1.I think some of these settings could be moved around/reworded slightly to make it clearer what they mean:
> a)"Use CommuniKate keyboard layout" should maybe read "Replace Alpha keyboard with CommuniKate"
> b)"Replace Alpha keyboard with CommuniKate" should be directly under "Enable CommuniKate keyboard layout"
> c)"Use simplified keyboard layout" should maybe read "Replace Alpha keyboard with simplified keyboard layout"
> d)"Use alphabetical keyboard layout" should maybe read "Use alphabetical alpha keyboard layout"
> e)These 3 settings (that change the alpha keyboard layout) should be mutually exclusive - if any is selected then the other two options should be set to false and not visible.

I agree to all of this. The alternative options do currently hide when one is chosen but they're not set to false. Normally making them just not visible should be enough but I suppose if there is an error in the config file it wouldn't hurt to be a bit more thorough and set hidden ones to false.

> 2.I think the output control (scratchpad etc) is too small. Can we rebalance the rows (by just adding a row and letting the output control span the same row height as all the CommuniKate keys. It feels a bit small at the moment.

It can certainly be a bit larger. I'll do it by setting [this row height](https://github.com/zelmon64/OptiKey/blob/6b601b672cf1024712ff1481e271add45dd150e3/src/JuliusSweetland.OptiKey/UI/Views/Keyboards/English/CommuniKate.xaml#L21) to 4 instead of 8 if that's okay.

> 3.The CommuniKate key selection animation colour is black - is this the colour that other CommuniKate devices use? It looks a bit odd/wrong to my eyes.

The problem with the red was that I didn't think it had enough contrast with the orange background of the question keys. From the CommuniKate demos I've tried there doesn't appear to be a selection animation. The options I thought of were to either set the selection colour relatively to the background colour (either completely opposite or some other specified offset) or to go with a fixed colour that works for all backgrounds (black seemed to be the only colour not used for a background). I went with the black to try to avoid colour-blindness issues but I'm open to suggestions. 

> 4.Once you enable CommuniKate, but leave UseCommuniKateKeyboardLayout=false, the first time you us the "CK" key then UseCommuniKateKeyboardLayout is set to true anyway. This makes it impossible to go back to the Alpha keyboard from the menu. I see you can get back there from 'My day' -> 'Spelling' (or 'My day' -> '123' to get the Numeric keyboard), but I still think this behaviour is wrong. If you quit OptiKey and then open it again I would expect the usual Alpha keyboard, but you get CommuniKate as your startup keyboard instead.

I agree this may be a bit jumbled. I think I can attain the functionality you want by adding another variable. The setting chosen the the management console would then be the default setting and the new variable would be a flag to indicate whether CommuniKate is currently on or off.

This would obviously be much simpler if the normal Alpha and Num/Sym keyboards weren't accessible when CommuniKate is enabled but I'm not sure if that's a good idea.

> 5.Should 'Spelling', '123', 'Computer Control' etc be under 'My day'? I don't know the boards, but this seems odds to me.

In the depersonalised version of CK20 that Joe made he completely remove `My day`. He also removed the `Leisure` pages. I was thinking of re-adding the `Leisure` pages and, since that also had a `Computer control` key, adding the `Spelling` and `123` key to that as well (or perhaps making a `Computer control` page which would have `Spelling`, `123` and `Mouse control`).

> a)'Delete word' key outputs "Delete Word" rather than actioning the BackMany function.
> b)This also begs the question; do we need the BackMany key if users will be expecting to use the CommuniKate 'Delete word' key? I don't have a strong opinion either way, just asking the question.

Here's the custom top page I've been using. I removed the `Delete word` key in favour of a `Yes` and `No` keys which are normally either side of the scratchpad but are in this position in the CoughDrop example. 
image

I haven't updated the included OBZ file yet as the depersonalised version isn't quite ready (it doesn't seem to include images) and I've been having some difficulty trying to make my own.

> 7.'Computer control' key outputs "Computer control" rather than changing the keyboard. Is this correct?

Again this is a change that needs to be made to the OBZ file 

> 8.The changes made to Android_Dark.xaml need to be mirrored (with different colours) into Android_Light.xaml

I haven't done this yet because I wasn't sure if Android_Dark was finished. After we decide how the selection animation should look I'll then mirror the changes into Android_Light.

> And some cleanup bits and bobs:
> 
> KeyboardCurrentContext setting looks to be unused - can we delete it?

It's not currently used but I was wondering about unifying how the Simplified Keyboard context is changed with this new method that the CommuniKate keyboard uses. I can delete it if you'd rather I do.

> Rename HandleMultiPropertyKeySelectionResult to HandleStringAndFunctionKeySelectionResult
> Rename UseCommuniKatedKeyboardLayoutIsVisible to UseCommuniKateKeyboardLayoutIsVisible

Yep I'll rename these (UseCommuniKate**d**KeyboardLayoutIsVisible is a funny typo)

> FunctionKeys.KeyboardContext looks to be unused - can we delete it?

Again this was intended for preparation of unifying the context control but it can be deleted if you'd prefer.

**Comment by zelmon64** [comment]
@JuliusSweetland I updated the OBZ archive with my changes so you can try it out but it's not the depersonalised version.

**Comment by JuliusSweetland** [comment]
Thank you for making the changes. It looks great! Here are my comments on the latest PR:

* I actually don't mind the black selection colour - I'll think about this some more, but maybe @joereddington can give us his opinon?
* Key.cs has a commented out line " //|| HasImage; } }" - could you remove for OCD reasons :)
* The changes made to Android_Dark.xaml need to be mirrored (with different colours) into Android_Light.xaml
* KeyboardCurrentContext setting looks to be unused - can we delete it?
    If you want to combine the context settings (Simplified and CommuniKate then that sounds like a great idea, but it's completely up to you.
* FunctionKeys.KeyboardContext looks to be unused - can we delete it?
    Again if you'd like to unify then great, but it's up to you.
* The layout of the CommuniKate looks the same as last time. It opened faster than last time - is it using the decompressed files from last run? If so how do I clean up so I can see your new changes? Also what happens if a user points to a new .obz pageset? Should OptiKey be able to clean up after itself?

**Comment by zelmon64** [comment]
> Key.cs has a commented out line " //|| HasImage; } }" - could you remove for OCD reasons :)

Sorry I forgot about this remnant. I'll remove it.

> The changes made to Android_Dark.xaml need to be mirrored (with different colours) into Android_Light.xaml

Since you're happy with the black animation I'll start on this. I'll set it to a white animation and we can see if it looks okay.

> KeyboardCurrentContext setting looks to be unused - can we delete it?
> If you want to combine the context settings (Simplified and CommuniKate then that sounds like a great idea, but it's completely up to you.
> FunctionKeys.KeyboardContext looks to be unused - can we delete it?
> Again if you'd like to unify then great, but it's up to you.

Thinking about it they might as well be removed as it'll be easy to add them again if/when I unify the context settings (or perhaps use the new dynamical method instead).

> The layout of the CommuniKate looks the same as last time. It opened faster than last time - is it using the decompressed files from last run? If so how do I clean up so I can see your new changes? Also what happens if a user points to a new .obz pageset? Should OptiKey be able to clean up after itself?

Oops I forgot to mention this sorry. I have it set to extract the pageset archive into a folder in `<OptiKey dir>/Resources/CommuniKate/<pageset archive name>`. This means it can switch between pagesets of different names easily but if a pageset is updated it's extracted folder has to be manually deleted so that OptiKey will unpack it again (or it can be manually unpacked). 

I did it this way because I didn't have much luck getting OptiKey to delete the folder automatically. I tried to trigger the deletion of the folder if a different OBZ archive is selected in the management console but nothing happened.

**Comment by JuliusSweetland** [comment]
That all sounds perfect. I'll try to find some time to test tomorrow.

**Comment by zelmon64** [comment]
@JuliusSweetland The only CK keys with a white background were the yes/no keys on the top page so I've changed them to a pale green/red. I used the same pale green as the `Delete word` key had and made the red by swapping the red and green values of that colour. What do you think? 

image

Mirroring the changes into `Android_Light.xaml` went a lot quicker and smoother than I thought it would.

**Comment by JuliusSweetland** [comment]
@zelmon64 I think it looks excellent. Nice work!

I'm struggling to find the unpacked files though. You said <OptiKey dir>/Resources/CommuniKate/<pageset archive name> but I can't find this in either the AppData Roaming folder, nor in Program Files (x86)?

**Comment by zelmon64** [comment]
@JuliusSweetland sorry. If you're building the debug version it's in "\OptiKey\src\JuliusSweetland.OptiKey\bin\Debug\Resources\CommuniKate\pageset". It'll be in Program Files (x86) when people install it.

I'm just adding a "previous page" key. It's working, I just have to commit it.
image

**Comment by JuliusSweetland** [comment]
Of course! I need to wake up!

Looks great. I'll try to check it in a bit.

**Comment by JuliusSweetland** [comment]
@zelmon64 I intend to review this tonight. Is it final state? In other words can I merge and release it if there are no issues?

**Comment by zelmon64** [comment]
@JuliusSweetland It should be ready for a release. I haven't notice any more that needs altering.

**Comment by JuliusSweetland** [comment]
@zelmon64 Great stuff. I'll look tonight.

**Comment by JuliusSweetland** [comment]
@zelmon64 Nearly there:

1.If you navigate from the alpha keyboard (or conversation alpha keyboard) to CommuniKate then the Back key does not take you back to alpha. Perhaps it shouldn't be on the top page?

2.Could you move the CK key on conversation alpha in line with the existing Yes/No key - both on the lower keys:

image

3.Is there any more cleaning up desired on the CommuniKate pages, e.g. placing the Back keys in consistent positions?

Otherwise I think it's ready to rock...

**Comment by JuliusSweetland** [comment]
@zelmon64 Could you also include this commit if it's easy to do?

https://github.com/OptiKey/OptiKey/commit/5112a442d49080f34bd677ae69abcf7c7080513f

**Comment by zelmon64** [comment]
@JuliusSweetland I agree I'll remove the back key from the CK top page and move the CK key on the alpha keyboard.

3. The CK back key is programmed to occupy the last empty key space. To make it consistent every page would have to be manually changed.

4. I'm not sure how to add a commit but I can definitely manually add the changes.

**Comment by JuliusSweetland** [comment]
You can leave the back key logic as it is. It's not a problem, just asking
the question.

I think this will be ready to merge after this.

**Comment by zelmon64** [comment]
@JuliusSweetland merging that commit was a lot easier than I thought it might be. 

I moved the `Things` CK page key back to it's original position and set the blank key to have a grey background.
image

**Comment by zelmon64** [comment]
@JuliusSweetland I was just checking through and I realised I didn't read your second point correctly last night. I moved the CK keyboard key on the ConversationAlpha keyboard to above the Yes/No key and moved it on the Alpha keyboard to next to the Q key. Is it okay to leave it like that or would you prefer I move the CK keyboard key to the same row as the Yes/No key?

**Comment by JuliusSweetland** [comment]
That sounds fine, thanks. I'll review this week.

**Comment by zelmon64** [comment]
@JuliusSweetland Turns out there was a bit more cleaning up to do on the CommuniKate pages. Hopefully that's all of it.

**Comment by JuliusSweetland** [comment]
Great thank you William. I'll review (and merge/release) on Friday. I
presume there is no more input from Joe?

**Pull request merged**
