### PR TITLE
Hungarian

### PR DESCRIPTION
**Pull request by N1Official**

### CODE REVIEW

**Comment by JuliusSweetland** [comment]
@N1Official Code review looks good. I will test the changes tomorrow and come back with any feedback. Hopefully we can get this released very quickly.

**Comment by JuliusSweetland** [comment]
@N1Official Hi Laszlo. Testing is good. I had a make 1 minor change, but everything looks great! This will be included in v2.31.0 which I will try to release in the next few days. Thank you! Can I ask what motivated you all to work on OptiKey and what it will be used for (if you have something specific in mind)?

**Comment by N1Official** [comment]
@JuliusSweetland Hi Julius. Of course! 🙂 The experience motivated us, because we are only a few students from an IT school. In the past 2 weeks I tried to motivate my teammates to write the code with me, but they were lazy so It was done by myself. We want to put in a key what can instantly translate and speak it out to the second/selected language correctly. 🤔

**Comment by JuliusSweetland** [comment]
@N1Official That's an interesting idea actually. It could be implemented with an addin and a new key to  be used in a dynamic keyboard. I'll create an issue to track this.

**Pull request merged**
