### PR TITLE
Add support for MaryTTS as discussed in #334

### PR DESCRIPTION
**Pull request by zelmon64**
[MaryTTS](https://github.com/marytts/marytts) is an alternative speech synthesizer that uses a java server with an HTTP interface instead of SAPI5. It has quite a few languages with rather good sounding voices. It comes with .bat files to start a GUI to install the desired voices and run the server.

To use MaryTTS with OptiKey get [marytts-5.2.zip](https://github.com/marytts/marytts/releases/download/v5.2/marytts-5.2.zip) (or later) and extract it to anywhere (such as "C:\MaryTTS\marytts-5.2\"). Then in Optikey's management console, under the Sounds tab, check `Use MaryTTS speech synthesizer` and press `FIND` to navigate to the unpacked `marytts-server.bat` ("C:\MaryTTS\marytts-5.2\bin\marytts-server.bat" in the example). After Optikey restarts a minimised cmd window will also be started containing the MaryTTS server and the available MaryTTS voices will be listed in the management console in the Sounds tab under `MaryTTS voice:`.

To install more MaryTTS voices run `marytts-component-installer.bat` ("C:\MaryTTS\marytts-5.2\bin\marytts-component-installer.bat" in the example).

### CODE REVIEW

**Comment by zelmon64** [comment]
Sorry I had a change to "src\JuliusSweetland.OptiKey\JuliusSweetland.OptiKey.csproj" which wasn't supposed to be there (line 915 `<LastGenOutput>Resources.Designer.cs</LastGenOutput>` got deleted somehow). It's fixed now.

**Comment by JuliusSweetland** [comment]
@zelmon64 I've only started looking into this PR and have a question for you; if you turn on exception handling in Visual Studio for ContextSwitchDeadlock do you encounter an exception on startup? If I prevent catching this exception in VS then everything looks fine, but this exception suggests something long running on the UI thread. I'll look further when I get a chance...

**Comment by zelmon64** [comment]
Is this the correct way to turn on exception handling in Visual Studio for ContextSwitchDeadlock?
image


I don't seem to be having any errors. Where would they appear?

**Comment by JuliusSweetland** [comment]
That's correct. If you we're encountering the exception it would be caught
by visual studio and displayed. I'll look into who I'm seeing it. Thanks.

**Comment by JuliusSweetland** [comment]
@zelmon64 Awesome PR. Merged. Thank you.

**Pull request merged**
