### PR TITLE
Dutch-Belgium

### PR DESCRIPTION
**Pull request by petermorlion**
This pull request includes a Dutch (Belgian) keyboard and language. It currently contains an empty dictionary file. I haven't yet searched for a way to easily and quickly populate a Dutch dictionary.

### CODE REVIEW

**Comment by JuliusSweetland** [comment]
Hi Peter. Are there huge variations from Netherlands' Dutch as I am currently trying to keep the supported languages as simple as possible. Let me know and I'll create you the appropriate branch (I create and test new languages, or big features, on separate feature branches until they are ready to merge into master and release).

Let me know, and thanks.

**Comment by petermorlion** [comment]
Well, in the Netherlands they use QWERTY keyboards. Possibly, you could re-use the French (AZERTY) keyboard. I'd have to take a look again, because they use more accented characters. But I do believe it would be possible, but currently can't compare because I'm at work.

I totally get you want to keep the languages limited.

Now while the keyboards in Belgium and the Netherlands differ, the language itsself doesn't realy. So nl-NL and nl-BE should have the same user interface language, it's just the keyboards that differ. And for that, you might be able to use the French keyboard. I'll check and let you know.

**Comment by JuliusSweetland** [comment]
If the keyboard language itself differs then I think it would be a good
idea to support both. I'll create you a new branch later today for you to
resubmit your pull request against.

**Comment by JuliusSweetland** [comment]
Hi Peter. I've created a new branch off master called 'Dutch' (https://github.com/OptiKey/OptiKey/tree/Dutch) can you please apply your changes onto that and submit a new pull request and then we can go from there.

I have created a new issue to track and discuss the Dutch work; https://github.com/OptiKey/OptiKey/issues/181

N.B. I am closing this pull request without merging your work. As above, please apply to the new branch and submit a new pull request. Thanks.

**Pull request closed without merging**
