### PR TITLE
Simplify Dictionary Data Structure

### PR DESCRIPTION
**Pull request by Chopinsky**
This PR aims to resolve issues of storing user entries and language dictionaries in 2 different levels, which will double the maintenance effort as well as storage space. Now entries storage has been all moved into `IAutoComplete` implementations and are exposed with proper APIs, `DictionaryService` will keep a reference to this storage for convenience use only.

### CODE REVIEW

**Comment by JuliusSweetland** [comment]
@Chopinsky Merged - thank you very much.

**Comment by JuliusSweetland** [comment]
@Chopinsky Hi Jacob - I've had to revert this merge as I'm afraid there is a performance problem when loading the dictionary on OptiKey startup. This was causing Visual Studio to raise a ContextSwitchDeadlock when running OptiKey. I can see the problem in the logs from these two log entries (which are next to each other) being 1.5 minutes apart when they should be seconds apart:

2017-07-28 10:11:18,711 [ 1] INFO  JuliusSweetland.OptiKey.Services.DictionaryService: LoadDictionary called. Keyboard language setting is 'EnglishUK'.
2017-07-28 10:11:22,740 [ 1] INFO  JuliusSweetland.OptiKey.Services.KeyStateService: Initialising KeyDownStates.

If you have a chance could you please take a look as I'd like to include your change? Thank you!

**Comment by Chopinsky** [comment]
Sure I will take a look.

**Comment by Chopinsky** [comment]
I will open another PR for this fix + the dict I/O upgrades.

**Comment by JuliusSweetland** [comment]
Great thanks Jacob.

**Pull request merged**
