### PR TITLE
Remove unused enums EyeXSensitivities and TaskbarPosition

### PR DESCRIPTION
**Pull request by adolfosilva**

### CODE REVIEW

**Comment by JuliusSweetland** [comment]
@adolfosilva Looks good, merging. Thanks.

**Comment by adolfosilva** [comment]
Hi @JuliusSweetland. I would like to contribute a bit more to this project. Add some tests, maybe write some documentation. Would you be able to give some mentoring help?

**Comment by JuliusSweetland** [comment]
@adolfosilva Sure. I can't offer too much time I'm afraid, but I can definitely oversee efforts if that sounds alright by you?

**Comment by adolfosilva** [comment]
Yes great, i understand. I just have a question for now. Why is the Enum + Extension Methods pattern used instead of using a Class?

**Comment by JuliusSweetland** [comment]
Can you give me an example of this and I'll explain the design

**Comment by adolfosilva** [comment]
For instance Enums/FunctionKeys.cs and Extensions/FunctionKeysExtensions.cs

**Comment by JuliusSweetland** [comment]
@adolfosilva I think my decision came from the fact that the value being passed around is just an int. Creating a class to hold a single enum value and a few "helper" methods just didn't seem appropriate to me, although this would be perfectly valid. I tend to use Extensions classes where the method is not necessarily core functionality of the data, but is instead more closely related to how that data is being used.

**Comment by adolfosilva** [comment]
@JuliusSweetland Ah makes sense. Thanks.

**Pull request merged**
