### PR TITLE
Updated translations, added 1of2 key

### PR DESCRIPTION
**Pull request by samgled**

### CODE REVIEW

**Comment by JuliusSweetland** [comment]
@samgled It's ok - I got your new PR. I'm preparing a pre-release build for you to test now. My initial tests look good.

**Comment by JuliusSweetland** [comment]
@samgled New pre-release version is available here: https://github.com/OptiKey/OptiKey/releases/tag/v2.16.0_pre-release_3

Could you please test and let me know.

**Comment by samgled** [comment]
Will do.

**Comment by samgled** [comment]
@JuliusSweetland 
I've had a quick check and everything looks good for the moment!

**Pull request merged**
