### PR TITLE
Implement feedback from original look-to-scroll pull request

### PR DESCRIPTION
**Pull request by joshlcampbell**
- Add new ScreenPoint bounds. Same as Screen (now ScreenCentered) except you choose where the deadzone gets placed.
- Add new Subwindow bounds. A combination of Window and Custom. You choose two points of the same window to form a rectangle. Scrolling only occurs while looking at that window.
- Re-order scroll modes: Free -> Cross -> Vertical -> Horizontal.
- Make Free mode and ScreenPoint bounds the defaults.
- Create setting to bring window under chosen screen point to front. Also, clarify the descriptions of the center mouse and the other bring window to front settings in light of new functionality.
- Create setting to control locked down behavior of bounds key. When not enabled (the default), the key acts as a simple cycle like the others.
- Remove format strings for LTS key text in favor of explicit text strings, and make the bounds key text more descriptive.
- Fix deadzone on overlay not matching deadzone in code. Combination of a DIP/pixel scaling issue -- using deadzones as pixels in the code but at the same time as DIPs in the XAML -- plus a stupid mistake of mine  -- the width/height of the on-screen rectangle should be _twice_ the deadzone size. If either was present on its own, I'd likely had noticed since I run in 4K with 250% scaling, but together they (mostly) canceled each other out.

Haven't had a chance to create the new icons for these two new bounds types yet, but I wanted to get this pull request opened up in the meantime. I'll fire up Inkscape tomorrow and get them added.

Thanks!

### CODE REVIEW

**Comment by joshlcampbell** [comment]
@JuliusSweetland I notice that I've been using American English spellings for the words "color" and "center" whereas the default UI language in OptiKey is EnglishUK. I plan on going back and changing occurrences in the default resource file and adding a new resource file for en-US, but I wanted to get your opinion about how they should be spelled in code (enums and the like) since the standard in C# and WPF seems to be the American English variants such as in System.Drawing.Color (thanks to my compatriots at Microsoft).

**Comment by JuliusSweetland** [comment]
@joshlcampbell Yeah UI strings are all in UK English. In code I, being English, lean towards UK spelling. It's really up to you.

**Comment by joshlcampbell** [comment]
UK spelling it is then :). I've replaced all occurrences of the US spellings with the UK ones in the code and resource strings added in my look to scroll work, and I've put US spellings for the resource strings into a new en-US resources file. I'll try to keep spelling in mind in any future work as well.

I've also pushed my updated icons for all of the types of bounds. Please let me know if you run into any issues with the updates.

Thanks!

**Comment by JuliusSweetland** [comment]
@joshlcampbell Looks great. I'll perform some proper testing tomorrow and prepare a release candidate. Thanks!

**Comment by JuliusSweetland** [comment]
@joshlcampbell Really strong PR again. Love it. Merged. Do you think you could formalise the instructions you've already written up and I'll add a new page to the Wiki so people know how to use it? If you have time you can fork the gh-pages branch and the PR back any images that you want to use in the page. That would be excellent!

Thanks again Josh - really really impressive.

**Comment by joshlcampbell** [comment]
Yup, that'll be my goal for the day today, and that clears up something I had been wondering about with the wiki: where I was going to put the images to link to!

**Pull request merged**
