### PR TITLE
Added more startup checks to MaryTTS

### PR DESCRIPTION
**Pull request by zelmon64**
* After trying to start the MaryTTS server, it is now checked that it was
started and hasn't been closed.

* If the MaryTTS server is closed before OptiKey, OptiKey nolonger tries
to close it.

* If MaryTTS is not available when the speak key is pressed, an attempt is
made to restart it. If this fails then MaryTTS is disabled.

@JuliusSweetland I only made these additions for #353 but they might be useful for future debugging. What do you think?

### CODE REVIEW

**Comment by JuliusSweetland** [comment]
@zelmon64 Couple of thoughts:

1. In CloseMaryTTSOnApplicationExit() why check again if the MaryTTS setting is enabled before closing the proc? This should always be safe to attempt, no?

2. In the Sound class there is an attempt to restart MaryTTS, but if this occurs then the process will not be closed when OptiKey exits. What do you think about refactoring out an extension method on the Process class which handles this for both scenarios (and any other processes that we want to spawn in future). Something like this;

`        private static void CloseOnApplicationExit(this Process proc, string description)
        {
            Current.Exit += (o, args) =>
            {
                if (proc.HasExited)
                {
                    Log.InfoFormat("{0} has already been closed.", description);
                }
                else
                {
                    try
                    {
                        proc.CloseMainWindow();
                        Log.InfoFormat("{0} has been closed.", description);
                    }
                    catch (Exception ex)
                    {
                        Log.Error(string.Format("Error closing {0} on OptiKey shutdown", description), ex);
                    }
                }
            };
        }`

**Comment by JuliusSweetland** [comment]
Actually I'll make this change as I want to test it quickly...

**Comment by JuliusSweetland** [comment]
I've added this change, and merged in @Chopinsky 's PR to update usage count when using Presage. Your fix when unpacking the CommuniKate boards has also been merged in. If you have a second could you please test the new v2.11.0 pre-release (3) here: https://github.com/OptiKey/OptiKey/releases

**Comment by zelmon64** [comment]
@JuliusSweetland v2.11.0 pre-release (3) seems to work very well. Thanks for finding a way to close the MaryTTS server when it has been restarted.

One thing I noticed though was that the dictionary list in the management console has repeated entries when set to Basic or NGram. The number each entry is repeated seems random. The EnglishUK.dic file is fine however.

**Comment by JuliusSweetland** [comment]
@Chopinsky do you know why the entries may be duplicated in the management
console? Thanks

**Comment by Chopinsky** [comment]
I think this may have something to do with normalizing entries. For example, Mike's and Mikes will be normalized into the same index and saved in the dictionary, and I think historically this is made by design to improve the search performance. 

I will take a look at how they're presented in the console, and that may very well be showing the entry index value instead of the entry object value.

**Comment by JuliusSweetland** [comment]
That sounds likely. Thanks Jacob.

**Comment by Chopinsky** [comment]
Looks like we're pulling all the normalized entries for NGram as well, that polluted the dictionary tab. I'm creating new PR to fix the issue. Base seems unaffected by this bug though.

**Comment by zelmon64** [comment]
@Chopinsky I just double checked and you are right about Basic being unaffected by this. My mistake.

**Pull request merged**
