### PR TITLE
added hebrew locale

### PR DESCRIPTION
**Pull request by idanrichman**
Hi,
added hebrew keyboards to this wonderful app

### CODE REVIEW

**Comment by idanrichman** [comment]
i left the UI language same as english (just copied and renamed the .resx file). 
although there is almost a full translation in transifex, i didn't felt it's good and ready enough to be in the product.

**Comment by JuliusSweetland** [comment]
@idanrichman Hi Idan. Your PR looks excellent, thank you! I'm going to pull it in and perform some testing. Would you have the time to finish/correct the Transifex translations and then I can integrate those and release it with another language that is ready to go?

2 quick questions also:
1.I believe there is no concept of casing in Hebrew, so  we could remove the SHIFT keys and replace them with something else? Unless SHIFT + Hebrew character can be used as part of a Windows shortcut or similar?
2.Does Hebrew have specific characters for numbers, or does it use latin numerics (1,2,3, etc)? If it has specific numbers (and other symbols) we can create a custom NumericAndSymbols1 keyboard, as I have done for Urdu or Farsi.

**Comment by JuliusSweetland** [comment]
@idanrichman One thing you may not know - if you change the UiLanguage (as well as the KeyboardLanguage) to Hebrew then OptiKey will correctly determine that typing should be right to left:

image

e.g.
image

**Comment by JuliusSweetland** [comment]
@idanrichman I've merged in your changes as they are and created a pre-release for you to test - it is the pre-release of v2.25.0: https://github.com/OptiKey/OptiKey/releases

**Comment by idanrichman** [comment]
> @idanrichman Hi Idan. Your PR looks excellent, thank you! I'm going to pull it in and perform some testing. Would you have the time to finish/correct the Transifex translations and then I can integrate those and release it with another language that is ready to go?

i'll try to go through transifex at least for the simple stuff. the advanced settings translations are just confusing.

 
> 2 quick questions also:
> 1.I believe there is no concept of casing in Hebrew, so we could remove the SHIFT keys and replace them with something else? Unless SHIFT + Hebrew character can be used as part of a Windows shortcut or similar?

in hebrew keyboard, usually the SHIFT + Hebrew character outputs the corresponding english character. i saw that in the xaml files there's ShiftDownText attribute which can show the english chars when shift is down, but there's only one value for a key... i guess that in the code itself it handles the upper/lower case for english keyboards. how do you suggest we could solve this?

> 2.Does Hebrew have specific characters for numbers, or does it use latin numerics (1,2,3, etc)? If it has specific numbers (and other symbols) we can create a custom NumericAndSymbols1 keyboard, as I have done for Urdu or Farsi.

no special chars. hebrew uses latin numerics.


and again, thank you very much, we're trying to use this app with a friend that had a stroke a few months ago and this could be very useful.

**Comment by JuliusSweetland** [comment]
@idanrichman Hi Idan. Ok I've changed the SHIFT key to a 1of2 key and added a second English keyboard which you can switch to. I've checked in all the changes and created a new version of 2.25.0: https://github.com/OptiKey/OptiKey/releases

**Comment by JuliusSweetland** [comment]
@idanrichman No rush, but did you see my comment above? If you're happy I'd like to release the new version of OptiKey this week. Thanks.

**Comment by idanrichman** [comment]
Hi, from what i've checked, the release version is ok.
sorry, didn't make it for the transifex validation.

**Comment by JuliusSweetland** [comment]
Oh I forgot about the Transifex translation. I would prefer to wait if you
think you'll have a chance to look at the translation?

**Comment by JuliusSweetland** [comment]
Hi Idan. If you don't have time, do you know of anyone who might be able to
help complete the Hebrew translation? I'm very keen to finish it now that
the keyboard etc are complete. It looks great.

**Comment by idanrichman** [comment]
Hi julius,
sorry for not being available, i'll finalize most of the translation in the
next couple of weeks.
i won't do the settings translation as its a much harder task to make it
clear and understandable in hebrew, and i think it's best for users to be
able to have the right to left support when shifting to hebrew UI, but
still having the settings in english (at least that was my experience when
i tried working with the current translation all-hebrew UI)

‫בתאריך יום ג׳, 13 באוג׳ 2019 ב-10:26 מאת ‪Julius‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by JuliusSweetland** [comment]
Hi Idan. No problem. Thanks for replying. It will be great when the
translation is ready. What do you mean by settings translations?

**Comment by idanrichman** [comment]
I mean the management console

בתאריך שבת, 31 באוג׳ 2019, 17:33, מאת Julius ‏<notifications@github.com>:

> Hi Idan. No problem. Thanks for replying. It will be great when the
> translation is ready. What do you mean by settings translations?
>

**Comment by JuliusSweetland** [comment]
@idanrichman Understood. Sounds good. The only issue may be that all text will be aligned right to left, but we can see how this is handled later.

**Comment by JuliusSweetland** [comment]
@idanrichman One more thing - would you please let me know when the Transifex translation is ready? I won't receive an automatic notification, so will almost certainly miss it. Thanks!

**Comment by idanrichman** [comment]
Hi Julius,
i've finished with the translation in transifex.
you can incorporate it

Thanks!
Idan

‫בתאריך יום ד׳, 4 בספט׳ 2019 ב-22:50 מאת ‪Julius‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by JuliusSweetland** [comment]
@idanrichman Great! Thank you very much! I am keen to release this asap so I may release a new version tonight.

Thanks again! Really appreciate it...

**Comment by JuliusSweetland** [comment]
@idanrichman I've checked and there are 57 untranslated strings. I presume these are intentional? Thanks.

**Comment by idanrichman** [comment]
Those are technical terms such as: "tobii eyeX" where there is no need to
translate them, or some settings strings that either i didnt understood and
didnt want to confuse with wrong translation or some long complex strings
that would end up long and cumbersome in hebrew.
I believe they are marginal. The most common and most used strings are
translated.

בתאריך יום ב׳, 23 בספט׳ 2019, 14:33, מאת Julius ‏<notifications@github.com>:

**Comment by JuliusSweetland** [comment]
@idanrichman Great, thanks again!

**Pull request merged**
